apiVersion: batch/v1
kind: Job
metadata:
  name: dsxe-simulation-batch-8-retry-1
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 4
  template:
    spec:
      containers:
      - name: dsxe-lob-simulation
        image: 588738568626.dkr.ecr.eu-west-2.amazonaws.com/dsxe-lob-simulation:latest
        resources:
          requests:
            memory: "3Gi"
            cpu: "1.5"
          limits:
            memory: "4Gi"
            cpu: "2"
        env:
        - name: CONFIG_START
          value: "3662"
        - name: CONFIG_END
          value: "3999"
        - name: TRIALS_PER_CONFIG
          value: "3"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws-secret-access-key
        - name: S3_BUCKET
          value: "dsxe-results"
      restartPolicy: OnFailure
